-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [clawdstrike]: function definitions
import Aeneas
import ClawdStrike.Impl.Types
import ClawdStrike.Impl.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace clawdstrike

/-- Trait implementation: [core::borrow::{core::borrow::Borrow<T> for T}]
    Source: '/rustc/library/core/src/borrow.rs', lines 212:0-212:37
    Name pattern: [core::borrow::Borrow<@T, @T>] -/
@[reducible, rust_trait_impl "core::borrow::Borrow<@T, @T>"]
def core.borrow.Borrow.Blanket (T : Type) : core.borrow.Borrow T T := {
  borrow := core.borrow.Borrow.Blanket.borrow
}

/-- Trait implementation: [core::fmt::{core::fmt::Display for str}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2958:0-2958:20
    Name pattern: [core::fmt::Display<str>] -/
@[reducible, rust_trait_impl "core::fmt::Display<str>"]
def Str.Insts.CoreFmtDisplay : core.fmt.Display Str := {
  fmt := Str.Insts.CoreFmtDisplay.fmt
}

/-- Trait implementation: [core::hash::impls::{core::hash::Hash for str}]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 862:4-862:21
    Name pattern: [core::hash::Hash<str>] -/
@[reducible, rust_trait_impl "core::hash::Hash<str>"]
def Str.Insts.CoreHashHash : core.hash.Hash Str := {
  hash := fun {H : Type} (HasherInst : core.hash.Hasher H) =>
    Str.Insts.CoreHashHash.hash HasherInst
}

/-- Trait implementation: [core::iter::adapters::enumerate::{core::iter::traits::iterator::Iterator<(usize, Clause0_Item)> for core::iter::adapters::enumerate::Enumerate<I>}]
    Source: '/rustc/library/core/src/iter/adapters/enumerate.rs', lines 62:0-64:16
    Name pattern: [core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<core::iter::adapters::enumerate::Enumerate<@I>, (usize, @Clause0_Item)>"]
def
  core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item
  {I : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst :
  core.iter.traits.iterator.Iterator I Clause0_Item) :
  core.iter.traits.iterator.Iterator (core.iter.adapters.enumerate.Enumerate I)
  (Std.Usize × Clause0_Item) := {
  next :=
    core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.next
    traitsiteratorIteratorInst
  step_by := fun self step => core.iter.traits.iterator.Iterator.step_by.default self step
  enumerate :=
    core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.enumerate
    traitsiteratorIteratorInst
  take := fun self n => sorry
}

/-- Trait implementation: [core::str::traits::{core::cmp::PartialEq<str> for str}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 27:0-27:28
    Name pattern: [core::cmp::PartialEq<str, str>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<str, str>"]
def Str.Insts.CoreCmpPartialEqStr : core.cmp.PartialEq Str Str := {
  eq := Str.Insts.CoreCmpPartialEqStr.eq
}

/-- Trait implementation: [core::str::traits::{core::cmp::Eq for str}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 36:0-36:21
    Name pattern: [core::cmp::Eq<str>] -/
@[reducible, rust_trait_impl "core::cmp::Eq<str>"]
def Str.Insts.CoreCmpEq : core.cmp.Eq Str := {
  partialEqInst := Str.Insts.CoreCmpPartialEqStr
  assert_receiver_is_total_eq :=
    Str.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- Trait implementation: [std::hash::random::{core::hash::Hasher for std::hash::random::DefaultHasher}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 125:0-125:29
    Name pattern: [core::hash::Hasher<std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::Hasher<std::hash::random::DefaultHasher>"]
def std.hash.random.DefaultHasher.Insts.CoreHashHasher : core.hash.Hasher
  std.hash.random.DefaultHasher := {
  finish := std.hash.random.DefaultHasher.Insts.CoreHashHasher.finish
  write := std.hash.random.DefaultHasher.Insts.CoreHashHasher.write
}

/-- Trait implementation: [std::hash::random::{core::hash::BuildHasher<std::hash::random::DefaultHasher> for std::hash::random::RandomState}]
    Source: '/rustc/library/std/src/hash/random.rs', lines 80:0-80:32
    Name pattern: [core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>] -/
@[reducible, rust_trait_impl
  "core::hash::BuildHasher<std::hash::random::RandomState, std::hash::random::DefaultHasher>"]
def std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher :
  core.hash.BuildHasher std.hash.random.RandomState
  std.hash.random.DefaultHasher := {
  HasherInst := std.hash.random.DefaultHasher.Insts.CoreHashHasher
  build_hasher :=
    std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher.build_hasher
}

/-- Trait implementation: [alloc::str::{core::borrow::Borrow<str> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/str.rs', lines 189:0-189:27
    Name pattern: [core::borrow::Borrow<alloc::string::String, str>] -/
@[reducible, rust_trait_impl
  "core::borrow::Borrow<alloc::string::String, str>"]
def alloc.string.String.Insts.CoreBorrowBorrowStr : core.borrow.Borrow String
  Str := {
  borrow := alloc.string.String.Insts.CoreBorrowBorrowStr.borrow
}

/-- Trait implementation: [alloc::string::{core::cmp::PartialEq<alloc::string::String> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 350:9-350:18
    Name pattern: [core::cmp::PartialEq<alloc::string::String, alloc::string::String>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<alloc::string::String, alloc::string::String>"]
def alloc.string.String.Insts.CoreCmpPartialEqString : core.cmp.PartialEq
  String String := {
  eq := alloc.string.String.Insts.CoreCmpPartialEqString.eq
}

/-- Trait implementation: [alloc::string::{core::cmp::Eq for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 350:32-350:34
    Name pattern: [core::cmp::Eq<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::cmp::Eq<alloc::string::String>"]
def alloc.string.String.Insts.CoreCmpEq : core.cmp.Eq String := {
  partialEqInst := alloc.string.String.Insts.CoreCmpPartialEqString
  assert_receiver_is_total_eq :=
    alloc.string.String.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- Trait implementation: [alloc::string::{core::fmt::Debug for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 2719:0-2719:26
    Name pattern: [core::fmt::Debug<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<alloc::string::String>"]
def alloc.string.String.Insts.CoreFmtDebug : core.fmt.Debug String := {
  fmt := alloc.string.String.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [alloc::string::{core::hash::Hash for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 2727:0-2727:26
    Name pattern: [core::hash::Hash<alloc::string::String>] -/
@[reducible, rust_trait_impl "core::hash::Hash<alloc::string::String>"]
def alloc.string.String.Insts.CoreHashHash : core.hash.Hash String := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    alloc.string.String.Insts.CoreHashHash.hash corehashHasherInst
}

/-- Trait implementation: [alloc::string::{core::convert::From<&0 (str)> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 3110:0-3110:26
    Name pattern: [core::convert::From<alloc::string::String, &'0 str>] -/
@[reducible, rust_trait_impl
  "core::convert::From<alloc::string::String, &'0 str>"]
def alloc.string.String.Insts.CoreConvertFromShared0Str : core.convert.From
  String Str := {
  from_ := alloc.string.String.Insts.CoreConvertFromShared0Str.from
}

/-- [clawdstrike::core::verdict::severity_ord]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 25:0-32:1 -/
def core.verdict.severity_ord
  (s : core.verdict.CoreSeverity) : Result Std.U8 := do
  match s with
  | core.verdict.CoreSeverity.Info => ok 0#u8
  | core.verdict.CoreSeverity.Warning => ok 1#u8
  | core.verdict.CoreSeverity.Error => ok 2#u8
  | core.verdict.CoreSeverity.Critical => ok 3#u8

/-- [clawdstrike::core::aggregate::aggregate_index]: loop body 0:
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 33:4-61:5 -/
@[rust_loop_body]
def core.aggregate.aggregate_index_loop.body
  (iter : core.iter.adapters.skip.Skip (core.iter.adapters.enumerate.Enumerate
  (core.slice.iter.Iter (Bool × core.verdict.CoreSeverity × Bool))))
  (best_idx : Std.Usize) (best : (Bool × core.verdict.CoreSeverity × Bool)) :
  Result (ControlFlow ((core.iter.adapters.skip.Skip
    (core.iter.adapters.enumerate.Enumerate (core.slice.iter.Iter (Bool ×
    core.verdict.CoreSeverity × Bool)))) × Std.Usize × (Bool ×
    core.verdict.CoreSeverity × Bool)) Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.adapters.skip.Skip.Insts.CoreIterTraitsIteratorIterator.next
      (core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item
      (core.iter.traits.iterator.IteratorSliceIter (Bool ×
      core.verdict.CoreSeverity × Bool))) iter
  match o with
  | none => ok (done best_idx)
  | some p =>
    let (idx, r) := p
    let (b, cs, b1) := best
    let (b2, cs1, b3) := r
    if ¬ b2
    then
      if ¬ b
      then
        if true = true
        then
          let i ← core.verdict.severity_ord cs1
          let i1 ← core.verdict.severity_ord cs
          if i > i1
          then ok (cont (iter1, idx, r))
          else
            if true = true
            then
              if i = i1
              then ok (cont (iter1, best_idx, best))
              else ok (cont (iter1, best_idx, best))
            else ok (cont (iter1, best_idx, best))
        else
          if true = true
          then
            let i ← core.verdict.severity_ord cs1
            let i1 ← core.verdict.severity_ord cs
            if i = i1
            then ok (cont (iter1, best_idx, best))
            else ok (cont (iter1, best_idx, best))
          else ok (cont (iter1, best_idx, best))
      else ok (cont (iter1, idx, r))
    else
      if false = (¬ b)
      then
        let i ← core.verdict.severity_ord cs1
        let i1 ← core.verdict.severity_ord cs
        if i > i1
        then ok (cont (iter1, idx, r))
        else
          if false = (¬ b)
          then
            if i = i1
            then
              if b3
              then
                if b1
                then ok (cont (iter1, best_idx, best))
                else ok (cont (iter1, idx, r))
              else ok (cont (iter1, best_idx, best))
            else ok (cont (iter1, best_idx, best))
          else ok (cont (iter1, best_idx, best))
      else
        if false = (¬ b)
        then
          let i ← core.verdict.severity_ord cs1
          let i1 ← core.verdict.severity_ord cs
          if i = i1
          then
            if b3
            then
              if b1
              then ok (cont (iter1, best_idx, best))
              else ok (cont (iter1, idx, r))
            else ok (cont (iter1, best_idx, best))
          else ok (cont (iter1, best_idx, best))
        else ok (cont (iter1, best_idx, best))

/-- [clawdstrike::core::aggregate::aggregate_index]: loop 0:
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 33:4-61:5 -/
@[rust_loop]
def core.aggregate.aggregate_index_loop
  (iter : core.iter.adapters.skip.Skip (core.iter.adapters.enumerate.Enumerate
  (core.slice.iter.Iter (Bool × core.verdict.CoreSeverity × Bool))))
  (best_idx : Std.Usize) (best : (Bool × core.verdict.CoreSeverity × Bool)) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, best_idx1, best1) => core.aggregate.aggregate_index_loop.body
      iter1 best_idx1 best1)
    (iter, best_idx, best)

/-- [clawdstrike::core::aggregate::aggregate_index]:
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 23:0-64:1 -/
def core.aggregate.aggregate_index
  (results : Slice (Bool × core.verdict.CoreSeverity × Bool)) :
  Result (Option Std.Usize)
  := do
  let b ← core.slice.Slice.is_empty results
  if b
  then ok none
  else
    let best ← Slice.index_usize results 0#usize
    let i ← core.slice.Slice.iter results
    let e ← core.slice.iter.IteratorSliceIter.enumerate i
    let iter ←
      core.iter.adapters.enumerate.Enumerate.Insts.CoreIterTraitsIteratorIteratorPairUsizeClause0_Item.skip
        (core.iter.traits.iterator.IteratorSliceIter (Bool ×
        core.verdict.CoreSeverity × Bool)) e 1#usize
    let best_idx ← core.aggregate.aggregate_index_loop iter 0#usize best
    ok (some best_idx)

/-- [clawdstrike::core::verdict::{clawdstrike::core::verdict::CoreVerdict}::allow]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 55:4-63:5 -/
def core.verdict.CoreVerdict.allow
  {T0 : Type} (coreconvertIntoT0StringInst : core.convert.Into T0 String)
  (guard : T0) :
  Result core.verdict.CoreVerdict
  := do
  let s ← coreconvertIntoT0StringInst.into guard
  let s1 ←
    alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay (toStr
      "Allowed")
  ok
    {
      allowed := true,
      severity := core.verdict.CoreSeverity.Info,
      sanitized := false,
      guard := s,
      message := s1
    }

/-- [clawdstrike::core::verdict::{core::clone::Clone for clawdstrike::core::verdict::CoreSeverity}::clone]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:9-7:14 -/
def core.verdict.CoreSeverity.Insts.CoreCloneClone.clone
  (self : core.verdict.CoreSeverity) : Result core.verdict.CoreSeverity := do
  ok self

/-- [clawdstrike::core::verdict::{core::clone::Clone for clawdstrike::core::verdict::CoreVerdict}::clone]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:9-38:14 -/
def core.verdict.CoreVerdict.Insts.CoreCloneClone.clone
  (self : core.verdict.CoreVerdict) : Result core.verdict.CoreVerdict := do
  let b ← lift (core.clone.impls.CloneBool.clone self.allowed)
  let cs ← core.verdict.CoreSeverity.Insts.CoreCloneClone.clone self.severity
  let b1 ← lift (core.clone.impls.CloneBool.clone self.sanitized)
  let s ← alloc.string.String.Insts.CoreCloneClone.clone self.guard
  let s1 ← alloc.string.String.Insts.CoreCloneClone.clone self.message
  ok
    { allowed := b, severity := cs, sanitized := b1, guard := s, message := s1
    }

/-- [clawdstrike::core::aggregate::aggregate_overall::{core::ops::function::FnMut<(&'_ (clawdstrike::core::verdict::CoreVerdict)), (bool, clawdstrike::core::verdict::CoreSeverity, bool)> for clawdstrike::core::aggregate::aggregate_overall::closure}::call_mut]:
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 76:13-76:53 -/
def
  core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnMutTupleSharedCoreVerdictTupleBoolCoreSeverityBool.call_mut
  (c : core.aggregate.aggregate_overall.closure)
  (tupled_args : core.verdict.CoreVerdict) :
  Result ((Bool × core.verdict.CoreSeverity × Bool) ×
    core.aggregate.aggregate_overall.closure)
  := do
  ok ((tupled_args.allowed, tupled_args.severity, tupled_args.sanitized), c)

/-- [clawdstrike::core::aggregate::aggregate_overall::{core::ops::function::FnOnce<(&'_ (clawdstrike::core::verdict::CoreVerdict)), (bool, clawdstrike::core::verdict::CoreSeverity, bool)> for clawdstrike::core::aggregate::aggregate_overall::closure}::call_once]:
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 76:13-76:53 -/
def
  core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnOnceTupleSharedCoreVerdictTupleBoolCoreSeverityBool.call_once
  (c : core.aggregate.aggregate_overall.closure)
  (cv : core.verdict.CoreVerdict) :
  Result (Bool × core.verdict.CoreSeverity × Bool)
  := do
  let (t, _) ←
    core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnMutTupleSharedCoreVerdictTupleBoolCoreSeverityBool.call_mut
      c cv
  ok t

/-- Trait implementation: [clawdstrike::core::aggregate::aggregate_overall::{core::ops::function::FnOnce<(&'_ (clawdstrike::core::verdict::CoreVerdict)), (bool, clawdstrike::core::verdict::CoreSeverity, bool)> for clawdstrike::core::aggregate::aggregate_overall::closure}]
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 76:13-76:53 -/
@[reducible]
def
  core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnOnceTupleSharedCoreVerdictTupleBoolCoreSeverityBool
  : core.ops.function.FnOnce core.aggregate.aggregate_overall.closure
  core.verdict.CoreVerdict (Bool × core.verdict.CoreSeverity × Bool) := {
  call_once :=
    core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnOnceTupleSharedCoreVerdictTupleBoolCoreSeverityBool.call_once
}

/-- Trait implementation: [clawdstrike::core::aggregate::aggregate_overall::{core::ops::function::FnMut<(&'_ (clawdstrike::core::verdict::CoreVerdict)), (bool, clawdstrike::core::verdict::CoreSeverity, bool)> for clawdstrike::core::aggregate::aggregate_overall::closure}]
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 76:13-76:53 -/
@[reducible]
def
  core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnMutTupleSharedCoreVerdictTupleBoolCoreSeverityBool
  : core.ops.function.FnMut core.aggregate.aggregate_overall.closure
  core.verdict.CoreVerdict (Bool × core.verdict.CoreSeverity × Bool) := {
  FnOnceInst :=
    core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnOnceTupleSharedCoreVerdictTupleBoolCoreSeverityBool
  call_mut :=
    core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnMutTupleSharedCoreVerdictTupleBoolCoreSeverityBool.call_mut
}

/-- [clawdstrike::core::aggregate::aggregate_overall]:
    Source: 'crates/libs/clawdstrike/src/core/aggregate.rs', lines 73:0-83:1 -/
def core.aggregate.aggregate_overall
  (results : Slice core.verdict.CoreVerdict) :
  Result core.verdict.CoreVerdict
  := do
  let i ← core.slice.Slice.iter results
  let m ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map
      core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnMutTupleSharedCoreVerdictTupleBoolCoreSeverityBool
      i ()
  let tuples ←
    core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
      (core.iter.traits.iterator.IteratorSliceIter core.verdict.CoreVerdict)
      core.aggregate.aggregate_overall.closure.Insts.CoreOpsFunctionFnMutTupleSharedCoreVerdictTupleBoolCoreSeverityBool
      (core.iter.traits.collect.FromIteratorVec (Bool ×
      core.verdict.CoreSeverity × Bool)) m
  let s := alloc.vec.Vec.deref tuples
  let o ← core.aggregate.aggregate_index s
  match o with
  | none =>
    core.verdict.CoreVerdict.allow (core.convert.IntoFrom
      alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr "engine")
  | some idx =>
    let cv ← Slice.index_usize results idx
    core.verdict.CoreVerdict.Insts.CoreCloneClone.clone cv

/-- [clawdstrike::core::cycle::MAX_POLICY_EXTENDS_DEPTH]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 10:0-10:47 -/
@[global_simps, irreducible]
def core.cycle.MAX_POLICY_EXTENDS_DEPTH : Std.Usize := 32#usize

/-- [clawdstrike::core::cycle::{core::clone::Clone for clawdstrike::core::cycle::CycleCheckResult}::clone]:
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:9-13:14 -/
def core.cycle.CycleCheckResult.Insts.CoreCloneClone.clone
  (self : core.cycle.CycleCheckResult) :
  Result core.cycle.CycleCheckResult
  := do
  match self with
  | core.cycle.CycleCheckResult.Ok => ok core.cycle.CycleCheckResult.Ok
  | core.cycle.CycleCheckResult.DepthExceeded __self_0 __self_1 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    let i1 ← lift (core.clone.impls.CloneUsize.clone __self_1)
    ok (core.cycle.CycleCheckResult.DepthExceeded i i1)
  | core.cycle.CycleCheckResult.CycleDetected __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (core.cycle.CycleCheckResult.CycleDetected s)

/-- Trait implementation: [clawdstrike::core::cycle::{core::clone::Clone for clawdstrike::core::cycle::CycleCheckResult}]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:9-13:14 -/
@[reducible]
def core.cycle.CycleCheckResult.Insts.CoreCloneClone : core.clone.Clone
  core.cycle.CycleCheckResult := {
  clone := core.cycle.CycleCheckResult.Insts.CoreCloneClone.clone
}

/-- [clawdstrike::core::cycle::{core::fmt::Debug for clawdstrike::core::cycle::CycleCheckResult}::fmt]:
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:16-13:21 -/
def core.cycle.CycleCheckResult.Insts.CoreFmtDebug.fmt
  (self : core.cycle.CycleCheckResult) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | core.cycle.CycleCheckResult.Ok =>
    core.fmt.Formatter.write_str f (toStr "Ok")
  | core.cycle.CycleCheckResult.DepthExceeded __self_0 __self_1 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_1
    core.fmt.Formatter.debug_struct_field2_finish f (toStr "DepthExceeded")
      (toStr "depth") __self_01 (toStr "limit") __self_11
  | core.cycle.CycleCheckResult.CycleDetected __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared alloc.string.String.Insts.CoreFmtDebug)
        __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "CycleDetected")
      (toStr "key") __self_01

/-- Trait implementation: [clawdstrike::core::cycle::{core::fmt::Debug for clawdstrike::core::cycle::CycleCheckResult}]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:16-13:21 -/
@[reducible]
def core.cycle.CycleCheckResult.Insts.CoreFmtDebug : core.fmt.Debug
  core.cycle.CycleCheckResult := {
  fmt := core.cycle.CycleCheckResult.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [clawdstrike::core::cycle::{core::marker::StructuralPartialEq for clawdstrike::core::cycle::CycleCheckResult}]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:23-13:32 -/
@[reducible]
def core.cycle.CycleCheckResult.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq core.cycle.CycleCheckResult := {
}

/-- [clawdstrike::core::cycle::{core::cmp::PartialEq<clawdstrike::core::cycle::CycleCheckResult> for clawdstrike::core::cycle::CycleCheckResult}::eq]:
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:23-13:32 -/
def core.cycle.CycleCheckResult.Insts.CoreCmpPartialEqCycleCheckResult.eq
  (self : core.cycle.CycleCheckResult) (other : core.cycle.CycleCheckResult) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | core.cycle.CycleCheckResult.Ok => ok true
    | core.cycle.CycleCheckResult.DepthExceeded __self_0 __self_1 =>
      match other with
      | core.cycle.CycleCheckResult.Ok => ok true
      | core.cycle.CycleCheckResult.DepthExceeded __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        if b
        then lift (core.cmp.impls.PartialEqUsize.eq __self_1 __arg1_1)
        else ok false
      | core.cycle.CycleCheckResult.CycleDetected _ => ok true
    | core.cycle.CycleCheckResult.CycleDetected __self_0 =>
      match other with
      | core.cycle.CycleCheckResult.Ok => ok true
      | core.cycle.CycleCheckResult.DepthExceeded _ _ => ok true
      | core.cycle.CycleCheckResult.CycleDetected __arg1_0 =>
        alloc.string.String.Insts.CoreCmpPartialEqString.eq __self_0 __arg1_0
  else ok false

/-- Trait implementation: [clawdstrike::core::cycle::{core::cmp::PartialEq<clawdstrike::core::cycle::CycleCheckResult> for clawdstrike::core::cycle::CycleCheckResult}]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:23-13:32 -/
@[reducible]
def core.cycle.CycleCheckResult.Insts.CoreCmpPartialEqCycleCheckResult :
  core.cmp.PartialEq core.cycle.CycleCheckResult core.cycle.CycleCheckResult
  := {
  eq := core.cycle.CycleCheckResult.Insts.CoreCmpPartialEqCycleCheckResult.eq
}

/-- [clawdstrike::core::cycle::{core::cmp::Eq for clawdstrike::core::cycle::CycleCheckResult}::assert_receiver_is_total_eq]:
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:34-13:36 -/
def core.cycle.CycleCheckResult.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : core.cycle.CycleCheckResult) : Result Unit := do
  ok ()

/-- Trait implementation: [clawdstrike::core::cycle::{core::cmp::Eq for clawdstrike::core::cycle::CycleCheckResult}]
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 13:34-13:36 -/
@[reducible]
def core.cycle.CycleCheckResult.Insts.CoreCmpEq : core.cmp.Eq
  core.cycle.CycleCheckResult := {
  partialEqInst :=
    core.cycle.CycleCheckResult.Insts.CoreCmpPartialEqCycleCheckResult
  assert_receiver_is_total_eq :=
    core.cycle.CycleCheckResult.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [clawdstrike::core::cycle::check_extends_cycle]:
    Source: 'crates/libs/clawdstrike/src/core/cycle.rs', lines 37:0-56:1 -/
def core.cycle.check_extends_cycle
  (key : Str)
  (visited : std.collections.hash.set.HashSet String
  std.hash.random.RandomState Global) (depth : Std.Usize) :
  Result core.cycle.CycleCheckResult
  := do
  if depth > core.cycle.MAX_POLICY_EXTENDS_DEPTH
  then
    ok (core.cycle.CycleCheckResult.DepthExceeded depth
      core.cycle.MAX_POLICY_EXTENDS_DEPTH)
  else
    let b ←
      std.collections.hash.set.HashSet.contains
        alloc.string.String.Insts.CoreCmpEq
        alloc.string.String.Insts.CoreHashHash
        std.hash.random.RandomState.Insts.CoreHashBuildHasherDefaultHasher
        alloc.string.String.Insts.CoreBorrowBorrowStr Str.Insts.CoreHashHash
        Str.Insts.CoreCmpEq visited key
    if b
    then
      let s ←
        alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay key
      ok (core.cycle.CycleCheckResult.CycleDetected s)
    else ok core.cycle.CycleCheckResult.Ok

/-- [clawdstrike::core::merge::{core::clone::Clone for clawdstrike::core::merge::CoreMergeStrategy}::clone]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:9-13:14 -/
def core.merge.CoreMergeStrategy.Insts.CoreCloneClone.clone
  (self : core.merge.CoreMergeStrategy) :
  Result core.merge.CoreMergeStrategy
  := do
  ok self

/-- Trait implementation: [clawdstrike::core::merge::{core::clone::Clone for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:9-13:14 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreCloneClone : core.clone.Clone
  core.merge.CoreMergeStrategy := {
  clone := core.merge.CoreMergeStrategy.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [clawdstrike::core::merge::{core::marker::Copy for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:16-13:20 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreMarkerCopy : core.marker.Copy
  core.merge.CoreMergeStrategy := {
  cloneInst := core.merge.CoreMergeStrategy.Insts.CoreCloneClone
}

/-- [clawdstrike::core::merge::{core::fmt::Debug for clawdstrike::core::merge::CoreMergeStrategy}::fmt]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:22-13:27 -/
def core.merge.CoreMergeStrategy.Insts.CoreFmtDebug.fmt
  (self : core.merge.CoreMergeStrategy) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | core.merge.CoreMergeStrategy.Replace =>
    core.fmt.Formatter.write_str f (toStr "Replace")
  | core.merge.CoreMergeStrategy.Merge =>
    core.fmt.Formatter.write_str f (toStr "Merge")
  | core.merge.CoreMergeStrategy.DeepMerge =>
    core.fmt.Formatter.write_str f (toStr "DeepMerge")

/-- Trait implementation: [clawdstrike::core::merge::{core::fmt::Debug for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:22-13:27 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreFmtDebug : core.fmt.Debug
  core.merge.CoreMergeStrategy := {
  fmt := core.merge.CoreMergeStrategy.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [clawdstrike::core::merge::{core::marker::StructuralPartialEq for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:29-13:38 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq core.merge.CoreMergeStrategy := {
}

/-- [clawdstrike::core::merge::{core::cmp::PartialEq<clawdstrike::core::merge::CoreMergeStrategy> for clawdstrike::core::merge::CoreMergeStrategy}::eq]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:29-13:38 -/
def core.merge.CoreMergeStrategy.Insts.CoreCmpPartialEqCoreMergeStrategy.eq
  (self : core.merge.CoreMergeStrategy) (other : core.merge.CoreMergeStrategy)
  :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [clawdstrike::core::merge::{core::cmp::PartialEq<clawdstrike::core::merge::CoreMergeStrategy> for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:29-13:38 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreCmpPartialEqCoreMergeStrategy :
  core.cmp.PartialEq core.merge.CoreMergeStrategy core.merge.CoreMergeStrategy
  := {
  eq := core.merge.CoreMergeStrategy.Insts.CoreCmpPartialEqCoreMergeStrategy.eq
}

/-- [clawdstrike::core::merge::{core::cmp::Eq for clawdstrike::core::merge::CoreMergeStrategy}::assert_receiver_is_total_eq]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:40-13:42 -/
def core.merge.CoreMergeStrategy.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : core.merge.CoreMergeStrategy) : Result Unit := do
  ok ()

/-- Trait implementation: [clawdstrike::core::merge::{core::cmp::Eq for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:40-13:42 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreCmpEq : core.cmp.Eq
  core.merge.CoreMergeStrategy := {
  partialEqInst :=
    core.merge.CoreMergeStrategy.Insts.CoreCmpPartialEqCoreMergeStrategy
  assert_receiver_is_total_eq :=
    core.merge.CoreMergeStrategy.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [clawdstrike::core::merge::{core::hash::Hash for clawdstrike::core::merge::CoreMergeStrategy}::hash]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:44-13:48 -/
def core.merge.CoreMergeStrategy.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : core.merge.CoreMergeStrategy) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [clawdstrike::core::merge::{core::hash::Hash for clawdstrike::core::merge::CoreMergeStrategy}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 13:44-13:48 -/
@[reducible]
def core.merge.CoreMergeStrategy.Insts.CoreHashHash : core.hash.Hash
  core.merge.CoreMergeStrategy := {
  hash := fun {__H : Type} (corehashHasherInst : core.hash.Hasher __H) =>
    core.merge.CoreMergeStrategy.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [clawdstrike::core::merge::child_overrides::{core::ops::function::FnOnce<(), core::option::Option<T>> for clawdstrike::core::merge::child_overrides::closure<0, T>[TraitClause@0]}::call_once]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 34:26-34:41 -/
def
  core.merge.child_overrides.closure.Insts.CoreOpsFunctionFnOnceTupleOption.call_once
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (c : core.merge.child_overrides.closure corecloneCloneInst) (_ : Unit) :
  Result (Option T)
  := do
  core.option.Option.Insts.CoreCloneClone.clone corecloneCloneInst c

/-- Trait implementation: [clawdstrike::core::merge::child_overrides::{core::ops::function::FnOnce<(), core::option::Option<T>> for clawdstrike::core::merge::child_overrides::closure<0, T>[TraitClause@0]}]
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 34:26-34:41 -/
@[reducible]
def core.merge.child_overrides.closure.Insts.CoreOpsFunctionFnOnceTupleOption
  {T : Type} (corecloneCloneInst : core.clone.Clone T) :
  core.ops.function.FnOnce (core.merge.child_overrides.closure
  corecloneCloneInst) Unit (Option T) := {
  call_once :=
    core.merge.child_overrides.closure.Insts.CoreOpsFunctionFnOnceTupleOption.call_once
    corecloneCloneInst
}

/-- [clawdstrike::core::merge::child_overrides]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 33:0-35:1 -/
def core.merge.child_overrides
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (base : Option T)
  (child : Option T) :
  Result (Option T)
  := do
  let o ←
    core.option.Option.Insts.CoreCloneClone.clone corecloneCloneInst child
  core.option.Option.or_else
    (core.merge.child_overrides.closure.Insts.CoreOpsFunctionFnOnceTupleOption
    corecloneCloneInst) o base

/-- [clawdstrike::core::merge::child_overrides_str]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 42:0-48:1 -/
def core.merge.child_overrides_str
  (base : Str) (child : Str) : Result String := do
  let b ← core.str.Str.is_empty child
  if b
  then alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay base
  else alloc.string.ToString.Blanket.to_string Str.Insts.CoreFmtDisplay child

/-- [clawdstrike::core::merge::child_overrides_option]:
    Source: 'crates/libs/clawdstrike/src/core/merge.rs', lines 55:0-57:1 -/
def core.merge.child_overrides_option
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (base : Option T)
  (child : Option T) :
  Result (Option T)
  := do
  core.option.Option.or child base

/-- Trait implementation: [clawdstrike::core::verdict::{core::clone::Clone for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:9-7:14 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreCloneClone : core.clone.Clone
  core.verdict.CoreSeverity := {
  clone := core.verdict.CoreSeverity.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [clawdstrike::core::verdict::{core::marker::Copy for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:16-7:20 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreMarkerCopy : core.marker.Copy
  core.verdict.CoreSeverity := {
  cloneInst := core.verdict.CoreSeverity.Insts.CoreCloneClone
}

/-- [clawdstrike::core::verdict::{core::fmt::Debug for clawdstrike::core::verdict::CoreSeverity}::fmt]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:22-7:27 -/
def core.verdict.CoreSeverity.Insts.CoreFmtDebug.fmt
  (self : core.verdict.CoreSeverity) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | core.verdict.CoreSeverity.Info =>
    core.fmt.Formatter.write_str f (toStr "Info")
  | core.verdict.CoreSeverity.Warning =>
    core.fmt.Formatter.write_str f (toStr "Warning")
  | core.verdict.CoreSeverity.Error =>
    core.fmt.Formatter.write_str f (toStr "Error")
  | core.verdict.CoreSeverity.Critical =>
    core.fmt.Formatter.write_str f (toStr "Critical")

/-- Trait implementation: [clawdstrike::core::verdict::{core::fmt::Debug for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:22-7:27 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreFmtDebug : core.fmt.Debug
  core.verdict.CoreSeverity := {
  fmt := core.verdict.CoreSeverity.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [clawdstrike::core::verdict::{core::marker::StructuralPartialEq for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:29-7:38 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq core.verdict.CoreSeverity := {
}

/-- [clawdstrike::core::verdict::{core::cmp::PartialEq<clawdstrike::core::verdict::CoreSeverity> for clawdstrike::core::verdict::CoreSeverity}::eq]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:29-7:38 -/
def core.verdict.CoreSeverity.Insts.CoreCmpPartialEqCoreSeverity.eq
  (self : core.verdict.CoreSeverity) (other : core.verdict.CoreSeverity) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [clawdstrike::core::verdict::{core::cmp::PartialEq<clawdstrike::core::verdict::CoreSeverity> for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:29-7:38 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreCmpPartialEqCoreSeverity :
  core.cmp.PartialEq core.verdict.CoreSeverity core.verdict.CoreSeverity := {
  eq := core.verdict.CoreSeverity.Insts.CoreCmpPartialEqCoreSeverity.eq
}

/-- [clawdstrike::core::verdict::{core::cmp::Eq for clawdstrike::core::verdict::CoreSeverity}::assert_receiver_is_total_eq]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:40-7:42 -/
def core.verdict.CoreSeverity.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : core.verdict.CoreSeverity) : Result Unit := do
  ok ()

/-- Trait implementation: [clawdstrike::core::verdict::{core::cmp::Eq for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:40-7:42 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreCmpEq : core.cmp.Eq
  core.verdict.CoreSeverity := {
  partialEqInst := core.verdict.CoreSeverity.Insts.CoreCmpPartialEqCoreSeverity
  assert_receiver_is_total_eq :=
    core.verdict.CoreSeverity.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [clawdstrike::core::verdict::{core::hash::Hash for clawdstrike::core::verdict::CoreSeverity}::hash]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:44-7:48 -/
def core.verdict.CoreSeverity.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : core.verdict.CoreSeverity) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  Isize.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [clawdstrike::core::verdict::{core::hash::Hash for clawdstrike::core::verdict::CoreSeverity}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 7:44-7:48 -/
@[reducible]
def core.verdict.CoreSeverity.Insts.CoreHashHash : core.hash.Hash
  core.verdict.CoreSeverity := {
  hash := fun {__H : Type} (corehashHasherInst : core.hash.Hasher __H) =>
    core.verdict.CoreSeverity.Insts.CoreHashHash.hash corehashHasherInst
}

/-- Trait implementation: [clawdstrike::core::verdict::{core::clone::Clone for clawdstrike::core::verdict::CoreVerdict}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:9-38:14 -/
@[reducible]
def core.verdict.CoreVerdict.Insts.CoreCloneClone : core.clone.Clone
  core.verdict.CoreVerdict := {
  clone := core.verdict.CoreVerdict.Insts.CoreCloneClone.clone
}

/-- [clawdstrike::core::verdict::{core::fmt::Debug for clawdstrike::core::verdict::CoreVerdict}::fmt]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:16-38:21 -/
def core.verdict.CoreVerdict.Insts.CoreFmtDebug.fmt
  (self : core.verdict.CoreVerdict) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugBool self.allowed
  let dyn1 :=
    Dyn.mk _ core.verdict.CoreSeverity.Insts.CoreFmtDebug self.severity
  let dyn2 := Dyn.mk _ core.fmt.DebugBool self.sanitized
  let dyn3 := Dyn.mk _ alloc.string.String.Insts.CoreFmtDebug self.guard
  let dyn4 :=
    Dyn.mk _ (core.fmt.DebugShared alloc.string.String.Insts.CoreFmtDebug)
      self.message
  core.fmt.Formatter.debug_struct_field5_finish f (toStr "CoreVerdict") (toStr
    "allowed") dyn (toStr "severity") dyn1 (toStr "sanitized") dyn2 (toStr
    "guard") dyn3 (toStr "message") dyn4

/-- Trait implementation: [clawdstrike::core::verdict::{core::fmt::Debug for clawdstrike::core::verdict::CoreVerdict}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:16-38:21 -/
@[reducible]
def core.verdict.CoreVerdict.Insts.CoreFmtDebug : core.fmt.Debug
  core.verdict.CoreVerdict := {
  fmt := core.verdict.CoreVerdict.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [clawdstrike::core::verdict::{core::marker::StructuralPartialEq for clawdstrike::core::verdict::CoreVerdict}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:23-38:32 -/
@[reducible]
def core.verdict.CoreVerdict.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq core.verdict.CoreVerdict := {
}

/-- [clawdstrike::core::verdict::{core::cmp::PartialEq<clawdstrike::core::verdict::CoreVerdict> for clawdstrike::core::verdict::CoreVerdict}::eq]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:23-38:32 -/
def core.verdict.CoreVerdict.Insts.CoreCmpPartialEqCoreVerdict.eq
  (self : core.verdict.CoreVerdict) (other : core.verdict.CoreVerdict) :
  Result Bool
  := do
  if self.allowed = other.allowed
  then
    if self.sanitized = other.sanitized
    then
      let b ←
        core.verdict.CoreSeverity.Insts.CoreCmpPartialEqCoreSeverity.eq
          self.severity other.severity
      if b
      then
        let b1 ←
          alloc.string.String.Insts.CoreCmpPartialEqString.eq self.guard
            other.guard
        if b1
        then
          alloc.string.String.Insts.CoreCmpPartialEqString.eq self.message
            other.message
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [clawdstrike::core::verdict::{core::cmp::PartialEq<clawdstrike::core::verdict::CoreVerdict> for clawdstrike::core::verdict::CoreVerdict}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:23-38:32 -/
@[reducible]
def core.verdict.CoreVerdict.Insts.CoreCmpPartialEqCoreVerdict :
  core.cmp.PartialEq core.verdict.CoreVerdict core.verdict.CoreVerdict := {
  eq := core.verdict.CoreVerdict.Insts.CoreCmpPartialEqCoreVerdict.eq
}

/-- [clawdstrike::core::verdict::{core::cmp::Eq for clawdstrike::core::verdict::CoreVerdict}::assert_receiver_is_total_eq]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:34-38:36 -/
def core.verdict.CoreVerdict.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : core.verdict.CoreVerdict) : Result Unit := do
  ok ()

/-- Trait implementation: [clawdstrike::core::verdict::{core::cmp::Eq for clawdstrike::core::verdict::CoreVerdict}]
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 38:34-38:36 -/
@[reducible]
def core.verdict.CoreVerdict.Insts.CoreCmpEq : core.cmp.Eq
  core.verdict.CoreVerdict := {
  partialEqInst := core.verdict.CoreVerdict.Insts.CoreCmpPartialEqCoreVerdict
  assert_receiver_is_total_eq :=
    core.verdict.CoreVerdict.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [clawdstrike::core::verdict::{clawdstrike::core::verdict::CoreVerdict}::block]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 67:4-79:5 -/
def core.verdict.CoreVerdict.block
  {T0 : Type} {T1 : Type} (coreconvertIntoT0StringInst : core.convert.Into T0
  String) (coreconvertIntoT1StringInst : core.convert.Into T1 String)
  (guard : T0) (severity : core.verdict.CoreSeverity) (message : T1) :
  Result core.verdict.CoreVerdict
  := do
  let s ← coreconvertIntoT0StringInst.into guard
  let s1 ← coreconvertIntoT1StringInst.into message
  ok
    { allowed := false, severity, sanitized := false, guard := s, message := s1
    }

/-- [clawdstrike::core::verdict::{clawdstrike::core::verdict::CoreVerdict}::warn]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 83:4-91:5 -/
def core.verdict.CoreVerdict.warn
  {T0 : Type} {T1 : Type} (coreconvertIntoT0StringInst : core.convert.Into T0
  String) (coreconvertIntoT1StringInst : core.convert.Into T1 String)
  (guard : T0) (message : T1) :
  Result core.verdict.CoreVerdict
  := do
  let s ← coreconvertIntoT0StringInst.into guard
  let s1 ← coreconvertIntoT1StringInst.into message
  ok
    {
      allowed := true,
      severity := core.verdict.CoreSeverity.Warning,
      sanitized := false,
      guard := s,
      message := s1
    }

/-- [clawdstrike::core::verdict::{clawdstrike::core::verdict::CoreVerdict}::sanitize]:
    Source: 'crates/libs/clawdstrike/src/core/verdict.rs', lines 95:4-103:5 -/
def core.verdict.CoreVerdict.sanitize
  {T0 : Type} {T1 : Type} (coreconvertIntoT0StringInst : core.convert.Into T0
  String) (coreconvertIntoT1StringInst : core.convert.Into T1 String)
  (guard : T0) (message : T1) :
  Result core.verdict.CoreVerdict
  := do
  let s ← coreconvertIntoT0StringInst.into guard
  let s1 ← coreconvertIntoT1StringInst.into message
  ok
    {
      allowed := true,
      severity := core.verdict.CoreSeverity.Warning,
      sanitized := true,
      guard := s,
      message := s1
    }

end clawdstrike
